plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'ghina.yassen.finaleproject'
    compileSdk  {
version=release(37)
    }

    defaultConfig {
        applicationId "ghina.yassen.finaleproject"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11

    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    //for room data base
    def room_version = "2.8.3"//"2.5.2"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
// optional - RxJava2 support for Room
    implementation "androidx.room:room-rxjava2:$room_version"
// optional - RxJava3 support for Room
    implementation "androidx.room:room-rxjava3:$room_version"
// optional - Guava support for Room, including Optional and ListenableFuture
    implementation "androidx.room:room-guava:$room_version"
// optional - Test helpers
    testImplementation "androidx.room:room-testing:$room_version"
// optional - Paging 3 Integration
    implementation "androidx.room:room-paging:$room_version"
}